# Generated by Django 3.0.7 on 2020-08-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetiontype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioncode', models.IntegerField()),
                ('title', models.TextField()),
                ('optiona', models.TextField()),
                ('optionb', models.TextField()),
                ('optionc', models.TextField()),
                ('optiond', models.TextField()),
                ('ans', models.TextField()),
                ('fkcoursemasterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseMaster')),
                ('fkquestiontypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionType')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examdate', models.DateField()),
                ('totalmarks', models.IntegerField()),
                ('totaltime', models.FloatField()),
                ('fkcoursemasterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseMaster')),
                ('fkexamtypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamType')),
            ],
        ),
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoredmarks', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
                ('fkadmissionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Admission')),
                ('fkexam_masterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamMaster')),
            ],
        ),
    ]
