CREATE TABLE Employee
(
	empid INT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    emailid VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8821,'George','Adamson ','george75@gmail.com','455ge16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8822,'Leslie','Alcock ','leslie424@gmail.com','12531le7');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8823,'Mick','Aston ','mick161@outlook.com','4059mi16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8824,'Richard','Atkinson ','richard518@gmail.com','10366ri1');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8825,'Edward','Russell','edward210@gmail.com','2127ed18');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8826,'Churchill','Babington ','churchill55@gmail.com','8298ch15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8827,'Philip','Arthur','philip280@gmail.com','3893ph17');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8828,'Thomas','Bateman ','thomas280@gmail.com','10923th4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8829,'James','Theodore','james585@outlook.com','15173ja7');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8830,'Geoffrey','Bibby ','geoffrey420@gmail.com','12451ge2');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8831,'Howard','Carter ','howard972@gmail.com','16475ho4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8832,'Grahame','Clark ','grahame667@gmail.com','11743gr7');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8833,'David','Clarke ','david891@gmail.com','10890da8');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8834,'Barry','Cunliffe ','barry944@gmail.com','6951ba9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8835,'Glyn','Daniel ','glyn649@outlook.com','5797gl15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8836,'John','Disney ','john348@gmail.com','3241jo13');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8837,'Cyril','Fox ','cyril641@gmail.com','14886cy14');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8838,'Dorothy','Garrod ','dorothy5@gmail.com','11484do13');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8839,'William','Greenwell ','william151@gmail.com','6156wi19');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8840,'Phil','Harding ','phil285@gmail.com','6975ph2');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8841,'Kathleen','Kenyon ','kathleen41@outlook.com','17727ka3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8842,'John','Leland ','john206@gmail.com','19393jo5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8843,'John','Lubbock ','john406@gmail.com','1706jo3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8844,'John','Robert','john828@gmail.com','9698jo19');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8845,'Francis','Pryor ','francis695@gmail.com','7888fr16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8846,'Colin','Renfrew ','colin749@gmail.com','11902co15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8847,'Alice','Roberts ','alice151@gmail.com','19731al10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8848,'Andrew','Sherratt ','andrew345@gmail.com','17206an13');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8849,'Mortimer','Wheeler ','mortimer311@gmail.com','17493mo12');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8850,'Hubert','Austin ','hubert324@gmail.com','11887hu11');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8851,'Charles','Barry ','charles969@gmail.com','466ch10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8852,'George','Basevi ','george920@outlook.com','9879ge13');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8853,'William','Burges ','william850@gmail.com','7780wi6');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8854,'William','Butterfield ','william780@gmail.com','14632wi9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8855,'Rowland','Carter ','rowland56@gmail.com','19221ro1');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8856,'William','Chambers ','william587@outlook.com','144wi8');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8857,'John','Douglas ','john347@gmail.com','5387jo20');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8858,'Henry','Flitcroft ','henry600@gmail.com','16628he20');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8859,'James','Harrison ','james650@outlook.com','2480ja19');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8860,'Thomas','Harrison ','thomas119@gmail.com','19423th9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8861,'Nicholas','Hawksmoor ','nicholas839@gmail.com','16359ni7');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8862,'Inigo','Jones ','inigo947@gmail.com','12609in19');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8863,'William','Kent ','william609@gmail.com','17248wi3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8864,'Edmund','Kirby ','edmund328@gmail.com','1816ed19');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8865,'Denys','Lasdun ','denys606@gmail.com','16278de18');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8866,'Thomas','Lockwood ','thomas522@gmail.com','3426th4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8867,'Edwin','Lutyens ','edwin487@outlook.com','8124ed8');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8868,'William','Morris ','william933@gmail.com','13711wi0');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8869,'John','Nash ','john624@gmail.com','7173jo0');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8870,'Henry','Paley ','henry939@gmail.com','17008he16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8871,'Joseph','Paxton ','joseph226@gmail.com','16834jo1');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8872,'Thomas','Mainwaring','thomas543@gmail.com','5574th10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8873,'August','Pugin ','august650@gmail.com','3085au1');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8874,'Anthony','Salvin ','anthony28@gmail.com','3649an5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8875,'George','Gilbert','george666@outlook.com','11581ge10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8876,'Giles','Gilbert','giles923@gmail.com','4898gi4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8877,'Edmund','Sharpe','edmund112@gmail.com','3121ed5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8878,'John','William','john554@gmail.com','3115jo9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8879,'George','Edmund','george347@gmail.com','19393ge12');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8880,'John','Vanbrugh','john562@gmail.com','11892jo16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8881,'Derek','Walker','derek882@outlook.com','2609de0');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8882,'Alfred','Waterhouse ','alfred467@gmail.com','13344al2');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8883,'Aston','Webb ','aston965@gmail.com','7464as10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8884,'William','Wilkins ','william977@gmail.com','16064wi9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8885,'Christopher','Wren ','christopher257@outlook.com','6295ch15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8886,'Sophie','Gengembre','sophie854@gmail.com','16471so6');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8887,'James','Andrews ','james493@outlook.com','17546ja0');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8888,'Richard','Ansdell ','richard590@gmail.com','5088ri3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8889,'Aubrey','Beardsley ','aubrey668@gmail.com','7138au3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8890,'Suzzan','Blac ','suzzan874@gmail.com','7721su2');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8891,'Sir Peter','Blake ','sir peter341@outlook.com','18774si6');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8892,'William','Blake ','william894@gmail.com','12381wi16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8893,'Henry','Charles','henry284@outlook.com','3706he12');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8894,'Sir Anthony','Caro ','sir anthony573@gmail.com','5665si5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8895,'Anna','Maria','anna138@gmail.com','8257an17');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8896,'John','Constable ','john71@gmail.com','18792jo20');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8897,'Tracey','Emin ','tracey975@gmail.com','6818tr7');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8898,'Thomas','Gainsborough ','thomas144@outlook.com','6832th4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8899,'Andy','Goldsworthy ','andy363@gmail.com','17921an9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8900,'Antony','Gormley OBE','antony496@gmail.com','2505an11');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8901,'James','Henry','james271@gmail.com','111ja11');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8902,'Steven','Harris ','steven393@gmail.com','3299st13');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8903,'Thomas','Hazlehurst ','thomas199@outlook.com','193th14');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8904,'Dame Barbara','Hepworth DBE','dame barbara967@gmail.com','6939da12');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8905,'Jamie','Hewlett ','jamie7@gmail.com','15565ja17');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8906,'Nicholas','Hilliard ','nicholas291@outlook.com','16898ni10');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8907,'Damien','Hirst ','damien254@gmail.com','17052da16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8908,'David','Hockney ','david567@outlook.com','4846da15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8909,'Sir Howard','Hodgkin ','sir howard602@gmail.com','639si9');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8910,'William','Hogarth ','william232@gmail.com','5580wi16');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8911,'Master','Hugo ','master812@gmail.com','7214ma20');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8912,'William','Holman','william394@gmail.com','2026wi20');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8913,'Sir Edwin','Landseer ','sir edwin415@outlook.com','2225si15');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8914,'Celia','Levetus ','celia457@gmail.com','19165ce4');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8915,'Richard','Long ','richard901@gmail.com','12566ri3');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8916,'Sir John','Everett','sir john613@gmail.com','17742si17');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8917,'Henry','Moore ','henry914@gmail.com','3780he5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8918,'William','Morris ','william192@gmail.com','19003wi5');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8919,'Lawrence','Mynott ','lawrence605@gmail.com','11649la2');
INSERT INTO Employee(empid,firstname,lastname,emailid,password)VALUES(8920,'Chris','Ofili ','chris568@outlook.com','1806ch5');
