# Generated by Django 3.0.7 on 2020-08-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='fkcatagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Catagory'),
            preserve_default=False,
        ),
    ]
