# Generated by Django 3.0.7 on 2020-08-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry', '0001_initial'),
        ('batch', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admndate', models.DateField()),
                ('coursefees', models.FloatField()),
                ('receivedfees', models.FloatField()),
                ('pendingfees', models.FloatField()),
                ('fkbatchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.Batch')),
                ('fkenqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Enquiry')),
                ('fktrainerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AdmissionStatus')),
            ],
        ),
    ]
